### ISSUE TITLE
Allow react-router ingore Kubernetes Ingress's path?

### ISSUE THREAD

**Issue by Kenzku** [ReactTraining/react-router#6037]
Hej,

It is a general issue about the relationship between Kubernetes Ingress proxy and react-router's UI routes.

For example,
I have an app using react-router, and I have a UI route like this

```jsx
      <Switch>
        <Route exact path="/" component={Home}/>
        <Route exact path={'/page1'} component={Page1}/>
        <Route path={'/page1/1'} component={Page1.1}/>
      </Switch>
```
It works fine e.g. on local host, deploy after nginx. However, if I would like to deploy on a Cloud platform behind on Kubernetes' Ingress proxy. I got some problem. For example, with the Ingress setting below. 

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: random-name-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 3000
        path: /ui
```

The following proxy hide my app behind /ui e.g. if my public ip is 9.37.xxx.xxx, my app will be available at, e.g. in the browser address bar, type in: https://9.37.xxx.xxx/ui

As my UI routes expecting / to home page, and /ui will not point to home page. It will actually point to nowhere.

I could add /ui or /other-context to my app's UI routes, but this will require code changes, and does not look like a good practise with Ingress in place. (There is a solution to just use / in the Ingress path config, but this is not the solution in some restricted environments.)

Please advise some practice.
