### ISSUE TITLE
Test on multiple React versions

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6388]
I'd like to run our tests on multiple versions of React in CI, if we can.

- Travis supports [build matrices](https://docs.travis-ci.com/user/customizing-the-build/#build-matrix) which we can use to run multiple jobs with different environment variables, so that should help.
- npm supports [a `--prefix` config option](https://docs.npmjs.com/misc/config#prefix) that we can use to change (I believe) the location where it looks for `package.json` and `node_modules`.

So we may be able to use these 2 features in combination to do something like this in our Travis config:

```yaml
env:
  - NPM_PREFIX=react-15
  - NPM_PREFIX=react-16
install:
  - npm install --prefix=$NPM_PREFIX
```

It seems a little hacky, and there would probably be some bugs to work out. But it might work.
